// <auto-generated />
using System;
using MedicalID.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalID.Backend.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicalID.Backend.Models.AccessLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<DateTime>("AccessTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PatientID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.ToTable("AccessLogs");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.Allergy", b =>
                {
                    b.Property<string>("PatientID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Allergen")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Reaction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientID", "Allergen");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.AskDoctor", b =>
                {
                    b.Property<string>("PatientID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MessageID")
                        .HasColumnType("int");

                    b.Property<string>("DoctorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RepliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientID", "MessageID");

                    b.HasIndex("DoctorID");

                    b.ToTable("AskDoctors");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.City", b =>
                {
                    b.Property<string>("CityID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityID");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.Doctor", b =>
                {
                    b.Property<string>("DoctorID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoctorID");

                    b.HasIndex("RegionID");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.Hospital", b =>
                {
                    b.Property<string>("HospitalID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("HospitalID");

                    b.HasIndex("RegionID");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.MedicalCondition", b =>
                {
                    b.Property<string>("PatientID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MedConditionID")
                        .HasColumnType("int");

                    b.Property<string>("ConditionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DiagnosedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientID", "MedConditionID");

                    b.ToTable("MedicalConditions");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.Medication", b =>
                {
                    b.Property<int>("MedicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicationID"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("PrescribedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MedicationID");

                    b.HasIndex("PatientID");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.Patient", b =>
                {
                    b.Property<string>("PatientID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OrganDonorStatus")
                        .HasColumnType("bit");

                    b.Property<string>("RegionID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PatientID");

                    b.HasIndex("RegionID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.RecordHistory", b =>
                {
                    b.Property<string>("PatientID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RecordID")
                        .HasColumnType("int");

                    b.Property<int?>("AccessLogID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientID", "RecordID");

                    b.HasIndex("AccessLogID");

                    b.HasIndex("DoctorID");

                    b.ToTable("RecordHistories");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.Region", b =>
                {
                    b.Property<string>("RegionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CityID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionID");

                    b.HasIndex("CityID");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.AccessLog", b =>
                {
                    b.HasOne("MedicalID.Backend.Models.Doctor", "Doctor")
                        .WithMany("AccessLogs")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalID.Backend.Models.Patient", "Patient")
                        .WithMany("AccessLogs")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.Allergy", b =>
                {
                    b.HasOne("MedicalID.Backend.Models.Patient", "Patient")
                        .WithMany("Allergies")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.AskDoctor", b =>
                {
                    b.HasOne("MedicalID.Backend.Models.Doctor", "Doctor")
                        .WithMany("AskDoctors")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalID.Backend.Models.Patient", "Patient")
                        .WithMany("AskDoctors")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.Doctor", b =>
                {
                    b.HasOne("MedicalID.Backend.Models.Region", "Region")
                        .WithMany("Doctors")
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.Hospital", b =>
                {
                    b.HasOne("MedicalID.Backend.Models.Region", "Region")
                        .WithMany("Hospitals")
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.MedicalCondition", b =>
                {
                    b.HasOne("MedicalID.Backend.Models.Patient", "Patient")
                        .WithMany("MedicalConditions")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.Medication", b =>
                {
                    b.HasOne("MedicalID.Backend.Models.Patient", "Patient")
                        .WithMany("Medications")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.Patient", b =>
                {
                    b.HasOne("MedicalID.Backend.Models.Region", null)
                        .WithMany("Patients")
                        .HasForeignKey("RegionID");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.RecordHistory", b =>
                {
                    b.HasOne("MedicalID.Backend.Models.AccessLog", "AccessLog")
                        .WithMany()
                        .HasForeignKey("AccessLogID");

                    b.HasOne("MedicalID.Backend.Models.Doctor", "Doctor")
                        .WithMany("RecordHistories")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalID.Backend.Models.Patient", "Patient")
                        .WithMany("RecordHistories")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessLog");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.Region", b =>
                {
                    b.HasOne("MedicalID.Backend.Models.City", "City")
                        .WithMany("Regions")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.City", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.Doctor", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("AskDoctors");

                    b.Navigation("RecordHistories");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.Patient", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("Allergies");

                    b.Navigation("AskDoctors");

                    b.Navigation("MedicalConditions");

                    b.Navigation("Medications");

                    b.Navigation("RecordHistories");
                });

            modelBuilder.Entity("MedicalID.Backend.Models.Region", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Hospitals");

                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
